import builtins from 'builtin-modules';
import esbuild from 'esbuild';
import { sassPlugin } from 'esbuild-sass-plugin';
import process from 'process';

const banner =
	`/*
Obsidian Rainbow Colored Sidebar
Copyright © 2025 Kevin Woblick <contact@kovah.de>
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
		css: banner
	},
	entryPoints: ['main.ts', 'styles.scss'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: '.',
	minify: prod,
	plugins: [sassPlugin()]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
